env:
  browser: true
  es2021: true
  node: true
extends: [
  'eslint:recommended',
  'plugin:prettier/recommended',
]
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-unused-vars:
    - error
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'